access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
spring:
  application:
    name: PafBackend
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb+srv://sandeepa678karunathilaka:AE6lz8zjkPBp1Fyv@cluster0.mqhzsg0.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: ${MONGODB_DB}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: 
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
logging:
  level:
    org.springframework.security: DEBUG
